DROP TABLE IF EXISTS trios CASCADE;
CREATE TABLE trios (
  id SERIAL PRIMARY KEY NOT NULL,
  name varchar(255) NOT NULL,
  player1_id INTEGER REFERENCES players(id) ON DELETE CASCADE,
  player2_id INTEGER REFERENCES players(id) ON DELETE CASCADE,
  player3_id INTEGER REFERENCES players(id) ON DELETE CASCADE 
);