INSERT INTO players(name) VALUES ('BBG Kreozard');
INSERT INTO players(name) VALUES ('sprite dabdabdba');
INSERT INTO players(name) VALUES ('C9 Avery');
INSERT INTO players(name) VALUES ('gаbeski');
INSERT INTO players(name) VALUES ('TUEXY');
INSERT INTO players(name) VALUES ('Cоmmandment');
INSERT INTO players(name) VALUES ('Fryst C9');
INSERT INTO players(name) VALUES ('NRG Edgey');
INSERT INTO players(name) VALUES ('FaZe Cented');
INSERT INTO players(name) VALUES ('PURE OSP7');
INSERT INTO players(name) VALUES ('Chimpま');
INSERT INTO players(name) VALUES ('twitter breadfn_');
INSERT INTO players(name) VALUES ('bully bully 39');
INSERT INTO players(name) VALUES ('SEN ZYFA 地');
INSERT INTO players(name) VALUES ('noob teyo');
INSERT INTO players(name) VALUES ('NRG ZAYT');
INSERT INTO players(name) VALUES ('Tabnae');
INSERT INTO players(name) VALUES ('TrainH saffy');
INSERT INTO players(name) VALUES ('nut 1300');
INSERT INTO players(name) VALUES ('Marzz_Ow');
INSERT INTO players(name) VALUES ('Liquid ЅТRETCН');
INSERT INTO players(name) VALUES ('LG Slackes');
INSERT INTO players(name) VALUES ('O zir vo');
INSERT INTO players(name) VALUES ('skqttles');
INSERT INTO players(name) VALUES ('Speguu');
INSERT INTO players(name) VALUES ('Cаzz');
INSERT INTO players(name) VALUES ('Liquid Riversan');
INSERT INTO players(name) VALUES ('XTRA Mero7');
INSERT INTO players(name) VALUES ('ENDL8SS DEYYRITO');
INSERT INTO players(name) VALUES ('ENDLESS Reverse');
INSERT INTO players(name) VALUES ('9LIVES Crumble');
INSERT INTO players(name) VALUES ('XTRA Illest');
INSERT INTO players(name) VALUES ('Avivv Yt');
INSERT INTO players(name) VALUES ('Trаshу');
INSERT INTO players(name) VALUES ('Justicе.');
INSERT INTO players(name) VALUES ('FS Ajerss');
INSERT INTO players(name) VALUES ('OUTCAST GOKU YT');
INSERT INTO players(name) VALUES ('C9 nosh');
INSERT INTO players(name) VALUES ('Twitch Vedfn');
INSERT INTO players(name) VALUES ('Pxlarized');
INSERT INTO players(name) VALUES ('XnBǃ');
INSERT INTO players(name) VALUES ('lеo 18');
INSERT INTO players(name) VALUES ('Snakeccept');
INSERT INTO players(name) VALUES ('Elite frat');
INSERT INTO players(name) VALUES ('LG Xoonies');
INSERT INTO players(name) VALUES ('XSET Shark');
INSERT INTO players(name) VALUES ('npen');
INSERT INTO players(name) VALUES ('XSET Knight');
INSERT INTO players(name) VALUES ('FS Degen');
INSERT INTO players(name) VALUES ('G2 Jаhq');
INSERT INTO players(name) VALUES ('1P Acornski');
INSERT INTO players(name) VALUES ('9LIVES Lazar');
INSERT INTO players(name) VALUES ('XSET Av');
INSERT INTO players(name) VALUES ('EP PAPE');
INSERT INTO players(name) VALUES ('A1 Silverback');
INSERT INTO players(name) VALUES ('divine ح');
INSERT INTO players(name) VALUES ('LG Jampеr ψ');
INSERT INTO players(name) VALUES ('A1 Ace1xx 〆');
INSERT INTO players(name) VALUES ('TNA ZLEM 3939');
INSERT INTO players(name) VALUES ('Elitе Crunchy');
INSERT INTO players(name) VALUES ('narwhаl');
INSERT INTO players(name) VALUES ('atomsG');
INSERT INTO players(name) VALUES ('twitter hctans');
INSERT INTO players(name) VALUES ('XPRT Domski');
INSERT INTO players(name) VALUES ('SEN Aspect.');
INSERT INTO players(name) VALUES ('yt duskyiwnl');
INSERT INTO players(name) VALUES ('Userz .');
INSERT INTO players(name) VALUES ('Dictate');
INSERT INTO players(name) VALUES ('CrackedNL');
INSERT INTO players(name) VALUES ('XPRT Equitz');
INSERT INTO players(name) VALUES ('Рrеdator');
INSERT INTO players(name) VALUES ('FаZe Bizzle');
INSERT INTO players(name) VALUES ('BBG Khanasty');
INSERT INTO players(name) VALUES ('G2 MackWood');
INSERT INTO players(name) VALUES ('NRG СІіх');
INSERT INTO players(name) VALUES ('SEN BUGHA 父');
INSERT INTO players(name) VALUES ('HIGHGROUND KІNG7');
INSERT INTO players(name) VALUES ('sto');
INSERT INTO players(name) VALUES ('Xen Squish7');
INSERT INTO players(name) VALUES ('steanzz');
INSERT INTO players(name) VALUES ('Сlamps');
INSERT INTO players(name) VALUES ('Mali Fan Adrian');
INSERT INTO players(name) VALUES ('chay5e');
INSERT INTO players(name) VALUES ('Noob Arkive');
INSERT INTO players(name) VALUES ('HunttCakee');
INSERT INTO players(name) VALUES ('Dukﱞe');
INSERT INTO players(name) VALUES ('Chap -α-');
INSERT INTO players(name) VALUES ('TRNL Threats');
INSERT INTO players(name) VALUES ('ENDLESS Pandush');
INSERT INTO players(name) VALUES ('c0dgenesis');
INSERT INTO players(name) VALUES ('9LIVES VOIL');
INSERT INTO players(name) VALUES ('KNG Nexy');
INSERT INTO players(name) VALUES ('BBG Bucke');
INSERT INTO players(name) VALUES ('SEN Animal');
INSERT INTO players(name) VALUES ('The Uzі');
INSERT INTO players(name) VALUES ('Cеicе');
INSERT INTO players(name) VALUES ('FS notpandda');
INSERT INTO players(name) VALUES ('DT Rise');
INSERT INTO players(name) VALUES ('tаhi');
INSERT INTO players(name) VALUES ('Unknown');
